
services:
  - type: web
    name: savings-app-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: savings-app-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: MPESA_CONSUMER_KEY
        sync: false
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_BUSINESS_SHORT_CODE
        sync: false
      - key: MPESA_PASSKEY
        sync: false
      - key: MPESA_CALLBACK_URL
        sync: false
      - key: SERVICE_FEE_MPESA_NUMBER
        value: 254796720095
      - key: POOL_MONEY_MPESA_NUMBER
        value: 254716841006
      - key: POOL_MONEY_BANK_ACCOUNT
        value: 006010159701
      - key: POOL_MONEY_THRESHOLD
        value: 150000

databases:
  - name: savings-app-db
    plan: starter
    databaseName: savings_app
    user: savings_user
